# 02. Univariate data

## Data-Driven Metrics

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../data/ch2_scores_em.csv',
                 index_col='student number')
# df의 처음 5행을 표시
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [5]:
scores = np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58])

In [6]:
scores_df = pd.DataFrame({'score':scores},
                         index=pd.Index(['A', 'B', 'C', 'D', 'E',
                                         'F', 'G', 'H', 'I', 'J'],
                                        name='student'))
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

### Average (Expected Value)

In [14]:
# PMF - Discrete random variable
# PDF - Continuous radom variable

# Expecatation has the linearity

### Median

In [7]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69])

In [9]:
n = len(sorted_scores)
if n % 2 == 0 :
    m0 = sorted_scores[n//2 - 1]
    m1 = sorted_scores[n//2]
    median = (m0 + m1) / 2
else :
    median = sorted_scores((n+1)// 2  - 1 )

median

56.5

### Mode

In [10]:
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [11]:
pd.Series([1, 2, 3, 4, 5]).mode()[1]

2

## Metrics of Data Variability

### Deviation

In [15]:
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [16]:
another_scores = [50, 60, 58, 54, 51, 56, 57, 53, 52, 59]
another_mean = np.mean(another_scores)
another_deviation = another_scores - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [17]:
np.mean(deviation)

0.0

In [18]:
summary_df = scores_df.copy()
summary_df['deviation'] = deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

In [19]:
summary_df.mean()

score        55.0
deviation     0.0
dtype: float64

### Variance
- It qantifies the spread or risk in outcomes and has predicatable behavior under linear transformations

In [20]:
np.mean(deviation ** 2)

86.0

In [21]:
np.var(scores)

86.0

In [ ]:
summary_df['square of deviation'] = np.square(deviation)
summary_df 

score  deviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
J           58        3.0                  9.0

In [23]:
summary_df.mean()

score                  55.0
deviation               0.0
square of deviation    86.0
dtype: float64

In [ ]:
# variation
np.mean(np.square(scores)) - np.mean(scores) ** 2 

86.0

### standard deviation

In [32]:
np.sqrt(np.var(scores, ddof = 0))

9.273618495495704

In [33]:
np.std(scores, ddof = 0)

9.273618495495704