# 03. 2-dimensional data

### Indicators that describe the relationship between two datasets
- Studnet who has high math score, has high english score?

In [3]:
import numpy as np
import pandas as pd

# %precision 3
# pd.set_option('precision', 3)

In [4]:
df = pd.read_csv('../data/ch2_scores_em.csv',
                 index_col='student number')

In [5]:
en_scores = np.array(df['english'])[:10]
ma_scores = np.array(df['mathematics'])[:10]

scores_df = pd.DataFrame({'english':en_scores,
                          'mathematics':ma_scores},
                         index=pd.Index(['A', 'B', 'C', 'D', 'E',
                                         'F', 'G', 'H', 'I', 'J'],
                                        name='student'))
scores_df

english  mathematics
student                      
A             42           65
B             69           80
C             56           63
D             41           63
E             57           76
F             48           60
G             65           81
H             49           66
I             65           78
J             58           82

### Covariance
- 부호를 붙인 면적

In [7]:
summary_df = scores_df.copy()
summary_df['english_deviation'] =\
    summary_df['english'] - summary_df['english'].mean()
summary_df['mathematics_deviation'] =\
    summary_df['mathematics'] - summary_df['mathematics'].mean()
summary_df['product of deviations'] =\
    summary_df['english_deviation'] * summary_df['mathematics_deviation']
summary_df

english  mathematics  english_deviation  mathematics_deviation  \
student                                                                   
A             42           65              -13.0                   -6.4   
B             69           80               14.0                    8.6   
C             56           63                1.0                   -8.4   
D             41           63              -14.0                   -8.4   
E             57           76                2.0                    4.6   
F             48           60               -7.0                  -11.4   
G             65           81               10.0                    9.6   
H             49           66               -6.0                   -5.4   
I             65           78               10.0                    6.6   
J             58           82                3.0                   10.6   

         product of deviations  
student                         
A                         83.2  
B                        120.4  
C                         -8.4  
D                        117.6  
E                          9.2  
F                         79.8  
G                         96.0  
H                         32.4  
I                         66.0  
J                         31.8

In [8]:
summary_df['product of deviations'].mean()

62.800

In [10]:
en_scores, ma_scores

(array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58]),
 array([65, 80, 63, 63, 76, 60, 81, 66, 78, 82]))

In [13]:
# covariance matrix or variance-covariance matrix
cov_mat = np.cov(en_scores, ma_scores, ddof = 0)
cov_mat

# Diagonal elements: variances of each variable
# cov_matrix[0,0] = 86.0 → Var(X) = 86
# cov_matrix[1,1] = 68.44 → Var(Y) = 68.44

# Off-diagonal elements: covariance between the two variables
# cov_matrix[0,1] = 62.8 → Cov(X,Y) = 62.8
# cov_matrix[1,0] = 62.8 → Cov(Y,X) = 62.8 (Covariance matrix is symmetric)

array([[86.  , 62.8 ],
       [62.8 , 68.44]])

In [15]:
cov_mat[0, 0], cov_mat[1, 1]

(86.000, 68.440)

In [16]:
np.var(en_scores, ddof = 0), np.var(ma_scores, ddof = 0)

(86.000, 68.440)