# The basics of inferential statistics

## 4.1 Population and sample

### 4.1.1 Method of sampling
- Estimator 
- Estimate

        → Estimate the population through a sample

- random sampling / independent and identically distributed
- sampling with replacement
- sampling without replacement

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%precision 3
%matplotlib inline

In [2]:
df = pd.read_csv('../data/ch4_scores400.csv')
scores = np.array(df['score'])
scores[:10]

array([76, 55, 80, 80, 74, 61, 81, 76, 23, 80])

In [10]:
# random & with replacement
np.random.choice([1, 2, 3], 3)

array([1, 3, 1])

In [9]:
# random & without replacement
np.random.choice([1, 2, 3], 3, replace=False)

array([2, 1, 3])

In [19]:
np.random.seed(0)
np.random.choice([1, 2, 3], 3)

array([1, 2, 1])

In [20]:
np.random.seed(0)
sample = np.random.choice(scores, 20)
sample.mean()

70.400

In [18]:
scores.mean()

69.530

In [22]:
for i in range(5):
    #np.random.seed(1)
    sample = np.random.choice(scores, 20)
    print(f'{i+1}번째 무작위 추출로 얻은 표본평균', sample.mean())

1번째 무작위 추출로 얻은 표본평균 74.4
2번째 무작위 추출로 얻은 표본평균 74.65
3번째 무작위 추출로 얻은 표본평균 70.95
4번째 무작위 추출로 얻은 표본평균 71.15
5번째 무작위 추출로 얻은 표본평균 70.1
